import { CompanySettings, Invoice } from '../types';
import { formatDate, numberToWords } from './formatters';

/**
 * Clean, bulletproof invoice printing utility.
 * Injects a standalone, self-contained printable DOM tree outside the React root,
 * applying pixel-perfect A4 typography, colors, and layout, and triggers window.print().
 */
export function printInvoiceDocument(
  invoice: Invoice,
  settings: CompanySettings,
  printedBy?: string
): void {
  if (!invoice) return;

  // Invoice creator / generated by name
  const creatorName = (invoice.created_by && invoice.created_by.trim()) || (printedBy && printedBy.trim()) || 'Authorized Officer';

  // Cleanup any leftover host
  const oldHost = document.getElementById('global-invoice-print-host');
  if (oldHost && oldHost.parentNode) {
    oldHost.parentNode.removeChild(oldHost);
  }

  // Format table rows
  const displayItems = [...invoice.items];
  const minRows = 8;
  const emptyRowsCount = Math.max(0, minRows - displayItems.length);
  const words = numberToWords(Math.round(invoice.total), settings.currency === 'BDT' ? 'Taka' : settings.currency);

  const theme = settings.invoice_theme || 'classic_minimal';

  const itemsHtml = displayItems
    .map(
      (item, idx) => `
    <tr style="background-color: ${idx % 2 === 0 ? '#ffffff' : '#f8fafc'}; font-size: 13px;">
      <td style="padding: 11px 12px; text-align: center; border-right: 1px solid #cbd5e1; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #334155;">
        ${String(idx + 1).padStart(2, '0')}
      </td>
      <td style="padding: 11px 14px; border-right: 1px solid #cbd5e1; border-bottom: 1px solid #e2e8f0;">
        <div style="font-weight: 700; color: #0f172a; font-size: 13.5px;">${item.item_name}</div>
        ${item.description ? `<div style="font-size: 11px; color: #64748b; margin-top: 2px; line-height: 1.4;">${item.description}</div>` : ''}
      </td>
      <td style="padding: 11px 12px; text-align: center; border-right: 1px solid #cbd5e1; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #334155;">
        ${item.quantity}
      </td>
      <td style="padding: 11px 12px; text-align: right; border-right: 1px solid #cbd5e1; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #334155;">
        ${item.unit_price.toLocaleString('en-US', { minimumFractionDigits: 2 })}
      </td>
      <td style="padding: 11px 14px; text-align: right; border-bottom: 1px solid #e2e8f0; font-weight: 700; color: #0f172a; font-size: 13.5px;">
        ${item.total.toLocaleString('en-US', { minimumFractionDigits: 2 })}
      </td>
    </tr>
  `
    )
    .join('');

  const emptyRowsHtml = Array.from({ length: emptyRowsCount })
    .map(
      (_, i) => `
    <tr style="background-color: ${(displayItems.length + i) % 2 === 0 ? '#ffffff' : '#f8fafc'}; height: 38px;">
      <td style="border-right: 1px solid #cbd5e1; border-bottom: 1px solid #e2e8f0;"></td>
      <td style="border-right: 1px solid #cbd5e1; border-bottom: 1px solid #e2e8f0;"></td>
      <td style="border-right: 1px solid #cbd5e1; border-bottom: 1px solid #e2e8f0;"></td>
      <td style="border-right: 1px solid #cbd5e1; border-bottom: 1px solid #e2e8f0;"></td>
      <td style="border-bottom: 1px solid #e2e8f0;"></td>
    </tr>
  `
    )
    .join('');

  // Generate Header HTML based on theme
  let headerHtml = '';
  let tableHeaderStyle = '';

  if (theme === 'full_banner') {
    headerHtml = `
      <div style="background-color: #0F3B2C; color: #ffffff; padding: 28px 34px; display: flex; justify-content: space-between; align-items: flex-start;">
        <div>
          <!-- Brand Logo -->
          <div style="font-family: 'Montserrat', 'Outfit', sans-serif; font-weight: 900; font-size: 42px; line-height: 0.95; letter-spacing: -0.04em; color: #ffffff;">Consultant</div>
          <div style="font-family: 'Outfit', 'Plus Jakarta Sans', sans-serif; font-size: 11.5px; letter-spacing: 0.45em; color: rgba(255, 255, 255, 0.95); margin-top: 6px; padding-left: 4px; text-transform: lowercase; font-weight: 600;">b y &nbsp; D &apos; R e x</div>
          
          <!-- Large bold INVOICE title -->
          <div style="font-family: 'Montserrat', 'Outfit', sans-serif; font-weight: 900; font-size: 46px; letter-spacing: -0.01em; line-height: 1; text-transform: uppercase; color: #ffffff; margin-top: 26px;">INVOICE</div>
        </div>
        
        <!-- Contact Info -->
        <div style="text-align: right; font-size: 13px; color: #f1f5f9; display: flex; flex-direction: column; gap: 8px; padding-top: 4px; font-weight: 500;">
          ${(settings.phone || settings.whatsapp) ? `<div style="display: flex; align-items: center; justify-content: flex-end; gap: 8px;"><span>${settings.phone || settings.whatsapp}</span></div>` : ''}
          <div style="display: flex; align-items: center; justify-content: flex-end; gap: 8px;"><span>${settings.email || 'consultantbydrexbd@gmail.com'}</span></div>
          ${settings.address ? `<div style="display: flex; align-items: center; justify-content: flex-end; gap: 8px; max-width: 280px; line-height: 1.35;"><span>${settings.address}</span></div>` : ''}
        </div>
      </div>
    `;
    tableHeaderStyle = `background-color: #0F3B2C; color: #ffffff; font-size: 13px; font-weight: 700; letter-spacing: 0.03em;`;
  } else if (theme === 'modern_compact') {
    headerHtml = `
      <div>
        <div style="height: 8px; background-color: #0F3B2C; width: 100%;"></div>
        <div style="background-color: #ffffff; color: #0f172a; padding: 26px 34px 22px 34px; border-bottom: 1px solid #e2e8f0; display: flex; justify-content: space-between; align-items: flex-start;">
          <div>
            <!-- Brand Logo in crisp black -->
            <div style="font-family: 'Montserrat', 'Outfit', sans-serif; font-weight: 900; font-size: 42px; line-height: 0.95; letter-spacing: -0.04em; color: #000000;">Consultant</div>
            <div style="font-family: 'Outfit', 'Plus Jakarta Sans', sans-serif; font-size: 11.5px; letter-spacing: 0.45em; color: #334155; margin-top: 6px; padding-left: 4px; text-transform: lowercase; font-weight: 600;">b y &nbsp; D &apos; R e x</div>
            
            <!-- Elegant Forest Green INVOICE Title -->
            <div style="font-family: 'Montserrat', 'Outfit', sans-serif; font-weight: 900; font-size: 44px; letter-spacing: -0.01em; line-height: 1; text-transform: uppercase; color: #0F3B2C; margin-top: 22px;">INVOICE</div>
          </div>
          
          <!-- Contact Info -->
          <div style="text-align: right; font-size: 13px; color: #334155; display: flex; flex-direction: column; gap: 7px; padding-top: 4px; font-weight: 500;">
            ${(settings.phone || settings.whatsapp) ? `<div style="display: flex; align-items: center; justify-content: flex-end; gap: 8px;"><span style="font-weight: 700; color: #0f172a;">${settings.phone || settings.whatsapp}</span></div>` : ''}
            <div style="display: flex; align-items: center; justify-content: flex-end; gap: 8px;"><span style="color: #475569;">${settings.email || 'consultantbydrexbd@gmail.com'}</span></div>
            ${settings.address ? `<div style="display: flex; align-items: center; justify-content: flex-end; gap: 8px; max-width: 300px; line-height: 1.35; color: #475569;"><span>${settings.address}</span></div>` : ''}
          </div>
        </div>
      </div>
    `;
    tableHeaderStyle = `background-color: #f1f5f9; color: #0f172a; font-size: 13px; font-weight: 800; letter-spacing: 0.03em; border-bottom: 2px solid #cbd5e1;`;
  } else {
    // classic_minimal (default pure white with crisp hairline accent)
    headerHtml = `
      <div>
        <div style="height: 6px; background-color: #0F3B2C; width: 100%;"></div>
        <div style="background-color: #ffffff; color: #0f172a; padding: 26px 34px 22px 34px; border-bottom: 2px solid #0f172a; display: flex; justify-content: space-between; align-items: flex-start;">
          <div>
            <!-- Brand Logo in black -->
            <div style="font-family: 'Montserrat', 'Outfit', sans-serif; font-weight: 900; font-size: 42px; line-height: 0.95; letter-spacing: -0.04em; color: #000000;">Consultant</div>
            <div style="font-family: 'Outfit', 'Plus Jakarta Sans', sans-serif; font-size: 11.5px; letter-spacing: 0.45em; color: #1e293b; margin-top: 6px; padding-left: 4px; text-transform: lowercase; font-weight: 600;">b y &nbsp; D &apos; R e x</div>
            
            <!-- Bold Ink-Saver INVOICE Title -->
            <div style="font-family: 'Montserrat', 'Outfit', sans-serif; font-weight: 900; font-size: 44px; letter-spacing: -0.01em; line-height: 1; text-transform: uppercase; color: #0F3B2C; margin-top: 22px;">INVOICE</div>
          </div>
          
          <!-- Contact Info -->
          <div style="text-align: right; font-size: 13px; color: #1e293b; display: flex; flex-direction: column; gap: 7px; padding-top: 4px; font-weight: 500;">
            ${(settings.phone || settings.whatsapp) ? `<div style="display: flex; align-items: center; justify-content: flex-end; gap: 8px;"><span style="font-weight: 700; color: #0f172a;">${settings.phone || settings.whatsapp}</span></div>` : ''}
            <div style="display: flex; align-items: center; justify-content: flex-end; gap: 8px;"><span style="color: #475569;">${settings.email || 'consultantbydrexbd@gmail.com'}</span></div>
            ${settings.address ? `<div style="display: flex; align-items: center; justify-content: flex-end; gap: 8px; max-width: 300px; line-height: 1.35; color: #475569;"><span>${settings.address}</span></div>` : ''}
          </div>
        </div>
      </div>
    `;
    tableHeaderStyle = `background-color: #f8fafc; color: #0f172a; font-size: 13px; font-weight: 800; letter-spacing: 0.03em; border-bottom: 2px solid #94a3b8;`;
  }

  const printDocumentHtml = `
    <div style="width: 210mm; min-height: 297mm; display: flex; flex-direction: column; justify-content: space-between; background: #ffffff; color: #0f172a; font-family: 'Plus Jakarta Sans', system-ui, -apple-system, sans-serif; box-sizing: border-box; margin: 0 auto; -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important;">
      <div>
        ${headerHtml}

        <!-- Meta section: Invoice To & Date -->
        <div style="padding: 24px 34px 18px 34px; display: flex; justify-content: space-between; align-items: flex-start;">
          <div>
            <div style="font-weight: 700; font-size: 15px; color: #0f172a; margin-bottom: 8px;">Invoice To</div>
            <div style="display: flex; font-size: 13px; margin-bottom: 4px;">
              <div style="width: 95px; color: #475569; font-weight: 500;">Client Name:</div>
              <div style="color: #0f172a; font-weight: 700;">${invoice.customer.name} ${invoice.customer.company_name ? `(${invoice.customer.company_name})` : ''}</div>
            </div>
            <div style="display: flex; font-size: 13px; margin-bottom: 4px;">
              <div style="width: 95px; color: #475569; font-weight: 500;">Phone:</div>
              <div style="color: #0f172a; font-weight: 600;">${invoice.customer.phone || '—'}</div>
            </div>
            <div style="display: flex; font-size: 13px; margin-bottom: 4px;">
              <div style="width: 95px; color: #475569; font-weight: 500;">Location:</div>
              <div style="color: #0f172a; font-weight: 500;">${invoice.customer.address || '—'}</div>
            </div>
          </div>

          <div>
            <div style="display: flex; justify-content: flex-end; font-size: 13px; margin-bottom: 4px;">
              <div style="text-align: right; margin-right: 8px; color: #475569; font-weight: 500;">Date:</div>
              <div style="color: #0f172a; font-weight: 700;">${formatDate(invoice.invoice_date)}</div>
            </div>
            <div style="display: flex; justify-content: flex-end; font-size: 13px; margin-bottom: 4px;">
              <div style="text-align: right; margin-right: 8px; color: #475569; font-weight: 500;">Invoice No:</div>
              <div style="color: #0F3B2C; font-weight: 700;">${invoice.invoice_number}</div>
            </div>
          </div>
        </div>

        <!-- Items Table -->
        <div style="padding: 0 34px;">
          <table style="width: 100%; border-collapse: collapse; border: 1px solid #cbd5e1;">
            <thead>
              <tr style="${tableHeaderStyle}">
                <th style="width: 52px; padding: 11px 12px; text-align: center; border-right: 1px solid #cbd5e1;">SL</th>
                <th style="padding: 11px 14px; text-align: left; border-right: 1px solid #cbd5e1;">Description</th>
                <th style="width: 65px; padding: 11px 12px; text-align: center; border-right: 1px solid #cbd5e1;">Qty</th>
                <th style="width: 110px; padding: 11px 12px; text-align: right; border-right: 1px solid #cbd5e1;">Fee</th>
                <th style="width: 125px; padding: 11px 14px; text-align: right;">Total</th>
              </tr>
            </thead>
            <tbody>
              ${itemsHtml}
              ${emptyRowsHtml}
            </tbody>
            <tfoot>
              <tr style="background-color: #f1f5f9; border-top: 2px solid #94a3b8; font-size: 13px;">
                <td colspan="3" style="padding: 13px 14px; border-right: 1px solid #cbd5e1;">
                  <span style="color: #0F3B2C; font-weight: 800; letter-spacing: 0.02em;">IN WORD: </span>
                  <span style="font-style: italic; color: #334155; font-weight: 600;">${words}</span>
                </td>
                <td style="padding: 13px 12px; text-align: right; border-right: 1px solid #cbd5e1; font-weight: 800; color: #0f172a;">
                  TOTAL
                </td>
                <td style="padding: 13px 14px; text-align: right; font-weight: 900; font-size: 15.5px; color: #0F3B2C;">
                  ${invoice.total.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                </td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>

      <!-- Footer Signature & Generation Section -->
      <div style="padding: 28px 34px 20px 34px; margin-top: auto; box-sizing: border-box;">
        <div style="display: flex; justify-content: flex-end; align-items: flex-end; margin-bottom: 18px;">
          <!-- Account Manager Signature -->
          <div style="display: flex; flex-direction: column; align-items: center; min-width: 190px;">
            <div style="width: 100%; border-top: 2px solid #0f172a; margin-bottom: 6px;"></div>
            <div style="font-family: 'Outfit', 'Plus Jakarta Sans', sans-serif; font-size: 13px; font-weight: 700; color: #0f172a; white-space: nowrap; text-align: center;">
              ${settings.account_manager_name || 'Account Manager'}
            </div>
          </div>
        </div>

        <!-- Bottom Official Verification Strip -->
        <div style="border-top: 1px solid #cbd5e1; padding-top: 8px; font-size: 11px; color: #475569;">
          This invoice was generated by <strong style="color: #0f172a; font-weight: 700;">${creatorName}</strong>
        </div>
      </div>
    </div>
  `;

  // Create clean host attached to body
  const printHost = document.createElement('div');
  printHost.id = 'global-invoice-print-host';
  printHost.innerHTML = printDocumentHtml;
  document.body.appendChild(printHost);

  // Trigger print after brief rendering pause
  setTimeout(() => {
    try {
      window.print();
    } catch (e) {
      console.warn('Direct print invocation error:', e);
    }
  }, 100);

  // Cleanup host afterwards
  const cleanup = () => {
    if (document.body.contains(printHost)) {
      document.body.removeChild(printHost);
    }
    window.removeEventListener('afterprint', cleanup);
  };

  window.addEventListener('afterprint', cleanup);
  setTimeout(cleanup, 10000);
}
